{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "waas.fullname" . }}-api
  namespace: {{ include "waas.namespace" . }}
  labels:
    {{- include "waas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "waas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "waas.fullname" . }}-delivery
  namespace: {{ include "waas.namespace" . }}
  labels:
    {{- include "waas.labels" . | nindent 4 }}
    app.kubernetes.io/component: delivery
spec:
  minAvailable: {{ .Values.podDisruptionBudget.delivery.minAvailable }}
  selector:
    matchLabels:
      {{- include "waas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: delivery
{{- end }}
